name: Build, Test and Version

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.11.0
      with:
        versionSpec: '5.x'

    - name: Run GitVersion
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.11.0

    - name: Show calculated version
      run: echo "GitVersion: ${{ steps.gitversion.outputs.fullSemVer }}"

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore /p:Version=${{ steps.gitversion.outputs.fullSemVer }}

    - name: Test
      run: dotnet test --no-build --verbosity normal
      continue-on-error: true

    - name: Publish artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: NetTools
        path: bin/Release/net9.0/

    - name: Copy LICENSE to output
      if: success()
      run: |
        copy LICENSE bin/Release/net9.0/win-x64/

    - name: Publish zip artifact
      if: success()
      run: |
        cd bin/Release/net9.0/win-x64
        7z a NetTools-${{ steps.gitversion.outputs.assemblySemVer }}.win-x64.zip * LICENSE

    - name: Upload zip to workflow artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: NetTools-zip
        path: bin/Release/net9.0/win-x64/NetTools-${{ steps.gitversion.outputs.assemblySemVer }}.win-x64.zip

    - name: Upload release to GitHub Releases
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: bin/Release/net9.0/win-x64/NetTools-${{ steps.gitversion.outputs.assemblySemVer }}.win-x64.zip
